#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
    path: /login
#
 #   path: /api/doc.json
#    methods: GET
 #   defaults: { _controller: nelmio_api_doc.controller.swagger }



